//
//  Readings.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Readings: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _timestamp: String?
    var _fEF: NSNumber?
    var _fEV75: NSNumber?
    var _fEV1: NSNumber?
    var _fEV1Best: NSNumber?
    var _fEV6: NSNumber?
    var _pEF: NSNumber?
    var _pEFBest: NSNumber?
    var _colorRating: String?
    var _goodBlow: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "pdm-mobilehub-1919196700-Readings"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_timestamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_timestamp" : "timestamp",
               "_fEF" : "FEF",
               "_fEV75" : "FEV,75",
               "_fEV1" : "FEV1",
               "_fEV1Best" : "FEV1_best",
               "_fEV6" : "FEV6",
               "_pEF" : "PEF",
               "_pEFBest" : "PEF_best",
               "_colorRating" : "color_rating",
               "_goodBlow" : "good_blow",
        ]
    }
}
